### ISSUE TITLE
simulated_example_nplcm.R fails

### ISSUE THREAD

**Issue by vjcitn** [zhenkewu/baker_example#1]
> gs <- nplcm(data_nplcm,model_options,mcmc_options)
> ==[baker] Results stored in: == 
>  ./scn_3_mixiter_1/rep_1_kfit_2 
> Error in names(tmp_alpha) <- colnames(Mobs$MBS[[s]]) : 
>   'names' attribute [6] must be the same length as the vector [1]
> In addition: Warning messages:
> 1: In dir.create(dated_strat_name) : './scn_3_mixiter_1' already exists
> 2: In dir.create(result_folder) :
>   './scn_3_mixiter_1/rep_1_kfit_2' already exists

Enter a frame number, or 0 to exit   

1: source("simulated_example_nplcm.R", echo = TRUE)
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(expr, envir, enclos)
5: simulated_example_nplcm.R#205: nplcm(data_nplcm, model_options, mcmc_option
6: nplcm_fit_NoReg(data_nplcm, model_options, mcmc_options)
7: set_prior_tpr_BrS_NoNest(i, model_options, data_nplcm)

**Comment by vjcitn** [comment]
Zhenke, will you be able to handle this?  Thanks

**Comment by zhenkewu** [comment]
Vince, thanks for the reminder! I found that JAGS has updated some of its syntax in specifying the iterators in a loop, which causes this bug. 

Also because baker has incorporated group-specific bronze-standard true positive rates (TPR), when specifying the alpha and beta parameters in the informative priors, we need to use 
something like: alpha = list(rep(6,10)) to accommodate multiple alphas, one per TPR group, instead of alpha = rep(6,10).

**Comment by vjcitn** [comment]
success?

**Comment by zhenkewu** [comment]
Updated and fixed.
